services:
  mysql94:
    image: mysql:8.0
    restart: always
    command:
      - --default_authentication_plugin=mysql_native_password
      - --binlog-format=ROW
      - --server-id=1
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      # 设置 MYSQL 配置文件
      # - ./mysql/conf:/etc/mysql/conf.d
      # 设置初始化脚本
      - ./:/docker-entrypoint-initdb.d/
    ports:
        # 映射端口
        - "3308:3306"

  # redis:
  #   image: bitnami/redis:latest
  #   # restart: always
  #   environment:
  #     #  不用密码
  #     - ALLOW_EMPTY_PASSWORD=yes
  #     # REDIS_PASSWORD: 123456
  #   ports:
  #     - "6379:6379"